image: j2a2m2all/guix-gitpod-doom-node:latest
ports:
  - port: 6080
    onOpen: open-browser
    visibility: public
  - port: 5900
    onOpen: ignore
tasks:
  - name: emacs
    before: /opt/gnu/bin/emacs -l ~/.emacs.d/init.el --eval="(all-the-icons-install-fonts 'y)" --kill
    command: /opt/gnu/bin/emacs -fs .gitpod.yml &
github:
  prebuilds:
    branches: true
    addBadge: true
