#+TITLE: Gitpod "Hello Emacs"

I have a few "works on my machine" type projects in python and javascript that I'd like to reproduce and pair with others on improving. I've also set up some custom workflows within emacs that I'd like others outside of emacs to interact with, either through self-serving exploration, or interactive demos. But I didn't just want to share specific apps or emacs appliances, I also wanted to empower others to use said appliances, and potentially build their own. So instead of asking others to bring their environment to me and hope for the best, I've brought my environment to everyone, courtesy of Gitpod.io!
* Setup
** Requirements
+ a browser (Chrome, Firefox)
+ a GitHub/GitLab/BitBucket account
** Quickstart
Navigate to the following link in your browser:

#+begin_src text
https://gitpod.io/#https://github.com/branjam4/gitpod-test
#+end_src
* Caveats
This particular version of my environment is best for people familiar with [[https://github.com/hlissner/doom-emacs][Doom
Emacs]], who want to poke around my environment and try out python/javascript code
(for example, from a development blog showcasing the python pandas module). But
one can make their own public repository and customize my =.gitpod.yml= file to
run a command which can demo their code. This is my intention for future
projects.
